image:
  repository: salisimiyu/simple-devops-project
  tag: 8048e4a
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false  